package com.sboot.sijak.last_payment;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.context.annotation.ComponentScan;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;



@SpringBootApplication

@MapperScan("com.sboot.sijak.last_payment.mapper")
@ComponentScan(basePackages = {"com.sboot.sijak", "com.other.package"}) // 추가할 패키지
@EnableDiscoveryClient
public class LastPaymentApplication implements CommandLineRunner {

	@Autowired
	private DataSource dataSource;

	public static void main(String[] args) {
		SpringApplication.run(LastPaymentApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		initializeDatabase();
	}

	// db 스키마 생성 
	public void initializeDatabase() {
		try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {

			// cart 테이블이 존재하는지 확인
			ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM user_tables WHERE table_name = 'CART'");
			if (!rs.next() || rs.getInt(1) == 0) {
				// cart 테이블 생성 SQL
				stmt.executeUpdate(
						"CREATE TABLE cart (cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_name VARCHAR2(100) NOT NULL, product_price NUMBER(6) NOT NULL)");
			}

			// payment_info 테이블이 존재하는지 확인
			rs = stmt.executeQuery("SELECT COUNT(*) FROM user_tables WHERE table_name = 'PAYMENT_INFO'");
			if (!rs.next() || rs.getInt(1) == 0) {
				// payment_info 테이블 생성 SQL
				stmt.executeUpdate(
						"CREATE TABLE payment_info (product_name VARCHAR2(100) NOT NULL, product_price NUMBER(6) NOT NULL, merchant_uid VARCHAR2(50) NOT NULL, purchase_date DATE NOT NULL, buyer_name VARCHAR(30) NOT NULL, buyer_tel VARCHAR(20) NOT NULL)");
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

}
