CREATE TABLE cart (
    cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    product_name VARCHAR2(100) NOT NULL,
    product_price NUMBER(6) NOT NULL,
    name VARCHAR2(20)
);

CREATE TABLE payment_info (
    product_name VARCHAR2(100) NOT NULL,
    product_price NUMBER(6) NOT NULL,
    merchant_uid VARCHAR2(50) NOT NULL,  -- 결제 고유 ID
    purchase_date DATE NOT NULL,
    buyer_name VARCHAR(30) NOT NULL,
    buyer_tel VARCHAR(20) NOT NULL
);